apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-cronjob
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: python-job
            image: darko0124/ my-spotify-script-container:latest
            command: ["python", "ETL_test.py"]  # Command to run your script
          restartPolicy: OnFailure
